pcall(require, "luarocks.loader")
local awful = require("awful")
require("awful.autofocus")
local beautiful = require("beautiful")
local paths = require("helpers.paths")
awful.spawn.with_shell(paths.to_script_autostart)
beautiful.init(paths.to_file_beautiful_theme)
require("config")
require("ui")
