-- Basic config
require("core.mappings")
require("core.plugins")
require("core.colors")
require("core.configs")

-- Plugins config
require("plugins.telescope")
require("plugins.lsp")
require("plugins.cmp")
require("plugins.lualine")
require("plugins.treesitter")
require("plugins.toggleterm")
require("plugins.outline")
require("plugins.autopairs")
require("plugins.comments")
require("plugins.autotag")
require("plugins.whichkey")
require("plugins.nvimtree")
require("plugins.mason")
require("plugins.cokeline")
-- require("plugins.themes")
require('plugins.mini_starter')
