[colors.bright]
black = "#112616"
red = "#7f2b27"
green = "#2f7e25"
yellow = "#bde000"
blue = "#2f6a7f"
magenta = "#327f77"
cyan = "#327f77"
white = "#647d75"

[colors.normal]
black = "#112616"
red = "#7f2b27"
green = "#2f7e25"
yellow = "#bde000"
blue = "#2f6a7f"
magenta = "#47587f"
cyan = "#327f77"
white = "#647d75"

[colors.primary]
background = "#172518"
foreground = "#637d75"