[colors.primary]
background = "#2D2424"
foreground = "#ffe9c7"

[colors.normal]
black = "#2d2424"
red = "#cf2241"
green = "#f07942"
yellow = "#e39c45"
blue = "#949f6b"
magenta = "#716c97"
cyan = "#ae3f8a"
white = "#9c8181"

[colors.bright]
black = "#725a5a"
red = "#e3556f"
green = "#f49d75"
yellow = "#edbf86"
blue = "#b0b893"
magenta = "#9894b3"
cyan = "#ca6bac"
white = "#ffe9c7"
