[colors.primary]
background: "#262626"
foreground: "#f0f0f0"

[colors.normal]
black: "#4c4c4c"
red: "#c49ea0"
green: "#9ec49f"
yellow: "#c4c19e"
blue: "#a5b4cb"
magenta: "#c49ec4"
cyan: "#9ec3c4"
white: "#f0f0f0"
    
[colors.bright]
black: "#4c4c4c"
red: "#ac8a8c"
green: "#8aac8b"
yellow: "#aca98a"
blue: "#8a98ac"
magenta: "#ac8aac"
cyan: "#8aacab"
white: "#e7e7e7"
