#!/usr/bin/env bash

bookdir="$HOME/.disk/Books/10 класс"
cd "$bookdir" || exit

selectpic() {
	book=$( ls "$bookdir" | cut -f 1 -d '.' |
	rofi -dmenu -i -p ">" -config ~/.config/awesome/other/rofi/configs/config.rasi)
		if [ "$book" ]; then
			chosenbook=$book
		else
			exit 0
		fi
}
selectpic

zathura "$( find "$bookdir" -name "$book*" )"
