#! /bin/sh

rofi_cmd() {
	rofi -dmenu \
		-theme ~/.config/awesome/other/rofi/configs/power.rasi
}

chosen=$(printf "\n\n\n" | rofi_cmd)

case "$chosen" in
	"") loginctl poweroff ;;
	"") loginctl reboot ;;
	"") awesome-client 'awesome.quit()' ;;
	"") loginctl suspend ;;
	*) exit 1 ;;
esac
